spring:
  datasource:
    a:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:postgresql://localhost:5432/test
      username: zbor
      password:
      driver-class-name: org.postgresql.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
    b:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:postgresql://localhost:5432/test2
      username: zbor
      password:
      driver-class-name: org.postgresql.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000